# 대구광역시 북구 공영주차장 운영 현황 및 현장 정보

## 전체 파이프라인 흐름
0. 환경설정 : 라이브러 불러오기, 경로, DB URL 설정
1. 수집 : csv 파일 읽기 (인코딩 --> 윈도 cp949)
2. 변환 : 파일에 따라
3. 파생컬럼(파생변수) : ex) 주차장명 / 소재지지번주소 / 주차구획수
4. 검증 : 유효성 검증 리포트 출럭
5. DB 저장 : postgreSQL -> parkinglotdb
6. csv 저장 : output폴더 안 csv파일(utf-8-sig)

In [2]:
import pandas as pd
from sqlalchemy import  create_engine, text
import os

BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_public parking lot'

In [21]:
DATA_PATH = os.path.join(BASE_DIR, 'input', 'parkinglot_raw.csv')
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_public parking lot\\input\\parkinglot_raw.csv'

In [20]:
OUTPUT_PATH = os.path.join(BASE_DIR, 'output', 'parkinglot_long.csv')
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_public parking lot\\output\\parkinglot_long.csv'

In [26]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/parkingdb'

In [27]:
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw.head()

,순번,주차장관리번호,주차장명,주차장 유형,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,주차기본요금,추가단위시간,추가단위요금,1일주차권요금적용시간,1일주차권적용시간,월정기요금,결제방법,관리기관명,경도,위도
0,1,154-1-000001,3공단로25길인근,노상,대구광역시 북구 노원동3가 191-1,6,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.897770,128.565410
1,2,154-1-000002,3공단로인근,노상,대구광역시 북구 노원동3가 14,329,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시청,35.899471,128.569853
2,3,154-1-000003,검단동로인근,노상,대구광역시 북구 검단동 745-2,29,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.913949,128.625135
3,4,154-1-000004,경대로17길인근,노상,대구광역시 북구 복현동 573,78,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892740,128.612720
4,5,154-1-000005,경대로23길인근,노상,대구광역시 북구 복현동 606-34,5,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892602,128.616021

In [23]:
df_raw.shape

(229, 27)

In [24]:
for i, col in enumerate(df_raw.columns):
    print(f'[{i}] {col}')

[0] 순번
[1] 주차장관리번호
[2] 주차장명
[3] 주차장 유형
[4] 소재지지번주소
[5] 주차구획수
[6] 급지구분
[7] 부제시행구분
[8] 운영요일
[9] 평일운영시작시각
[10] 평일운영종료시각
[11] 토요일운영시작시각
[12] 토요일운영종료시각
[13] 공휴일운영시작시각
[14] 공유일운영종료시각
[15] 요금정보
[16] 주차기본시간
[17] 주차기본요금
[18] 추가단위시간
[19] 추가단위요금
[20] 1일주차권요금적용시간
[21] 1일주차권적용시간
[22] 월정기요금
[23] 결제방법
[24] 관리기관명
[25] 경도
[26] 위도

In [25]:
df_raw.dtypes

순번               int64
주차장관리번호            str
주차장명               str
주차장 유형             str
소재지지번주소            str
주차구획수            int64
급지구분             int64
부제시행구분             str
운영요일               str
평일운영시작시각           str
평일운영종료시각           str
토요일운영시작시각          str
토요일운영종료시각          str
공휴일운영시작시각          str
공유일운영종료시각          str
요금정보               str
주차기본시간           int64
주차기본요금           int64
추가단위시간           int64
추가단위요금           int64
1일주차권요금적용시간      int64
1일주차권적용시간        int64
월정기요금            int64
결제방법               str
관리기관명              str
경도             float64
위도             float64
dtype: object

In [28]:
null_counts = df_raw.isnull().sum()
if null_counts.any():
    print('결측치 발견:(')
    print(null_counts[null_counts > 0])
else:
    print('결측치 없음:)')

결측치 없음:)

In [33]:
df_save = df_raw[['주차장명', '소재지지번주소', '주차구획수']]
df_save.head()

        주차장명               소재지지번주소  주차구획수
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6
1     3공단로인근     대구광역시 북구 노원동3가 14    329
2     검단동로인근    대구광역시 북구 검단동 745-2     29
3   경대로17길인근      대구광역시 북구 복현동 573     78
4   경대로23길인근   대구광역시 북구 복현동 606-34      5

In [54]:
df_long = pd.melt(
    df_raw, id_vars=['주차장명', '소재지지번주소'], value_vars=['주차구획수'], var_name='구분', value_name='값'   
)

df_long.head()

        주차장명               소재지지번주소     구분    값
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1  주차구획수    6
1     3공단로인근     대구광역시 북구 노원동3가 14  주차구획수  329
2     검단동로인근    대구광역시 북구 검단동 745-2  주차구획수   29
3   경대로17길인근      대구광역시 북구 복현동 573  주차구획수   78
4   경대로23길인근   대구광역시 북구 복현동 606-34  주차구획수    5

In [60]:
def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()

for col in df_save.columns:
    if pd.api.types.is_string_dtype(df_save[col]):
        df_save[col] = df_save[col].astype(str)
engine = create_engine(DB_URL)

with engine.connect () as conn:
    version = conn.execute(text('SELECT version();')).fetchone()[0]
    print('PostgreSQL 연결성공')
    print(version[:80] + '...')

    df_save.to_sql(
        name='parking_lot',  
        con=engine,           
        if_exists='replace',  
        index=False,          
        method='multi' 
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM parking_lot;')).fetchone()[0]

    print(f'저장 완료 {saved_count}')
    print(f'DB : parkingdb / table : parking_lot')

PostgreSQL 연결성공
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료 229
DB : parkingdb / table : parking_lot

In [58]:
TABLE_NAME = 'parking-raw'

In [59]:
df_long.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료')
print(f'경로: {OUTPUT_PATH}')
print(f'크기: {len(df_long):,}행 x {len(df_long.columns)}열')

CSV 저장 완료
경로: c:\Users\Administrator\bigdata2026\fastapi\02_public parking lot\output\parkinglot_long.csv
크기: 229행 x 4열