# 5.8 연습문제

In [1]:
# 문제2
import pandas as pd
filename='covid.csv'
df=pd.read_csv(filename,encoding='cp949')
df
#1.항목열을 인덱스열로 지정한 후 ‘스마트폰’의 해당하는 모든 컬럼의 정보를 출력해보자.
df=pd.read_csv(filename,index_col=0,encoding='cp949')
df
#2.사례수가 가장 높은 항목의 모든 정보를 출력해보자.
result=df[df['사례수']==df['사례수'].max()]
result
#3.증가율이 높은 3개의 항목을 출력해보자.
newdata=df.sort_values('증가',ascending=False)
newdata.head(3)

        사례수    증가   감소  변화없음
항목
스마트폰    999  78.9  1.7  19.4
텔레비전    965  68.5  3.9  27.6
개인용 PC  973  65.7  3.7  30.6

In [3]:
#문제3-1
import pandas as pd
import matplotlib.pyplot as plt

filename='vaccine.csv'
vaccine=pd.read_csv(filename,encoding='cp949')
vaccine

,date,subject,day1num,day1sum,day1rate,day2num,day2sum,day2rate
0,2021.10.16,9505868,10673,7562283,79.6,66910,6191341,65.1
1,2021.10.15,9505868,14556,7551829,79.4,133580,6124432,64.4
2,2021.10.14,9505868,9609,7536654,79.3,94569,5989111,63.0
3,2021.10.13,9505868,9804,7526430,79.2,77503,5893191,62.0
4,2021.10.12,9505868,17274,7516070,79.1,110204,5814018,61.2
...,...,...,...,...,...,...,...,...
174,2021.04.25,1023346,23323,350631,34.2,3411,18513,1.8
175,2021.04.24,1023346,200,350427,34.2,0,18513,1.8
176,2021.04.23,1027740,10195,345764,33.6,119,18376,1.8
177,2021.04.22,1023538,27074,317386,31.0,2479,15901,1.6
178,2021.04.21,1019322,22501,291857,28.6,2358,13543,1.3

In [5]:
# 문제3-2

import pandas as pd
import matplotlib.pyplot as plt

filename='vaccine.csv'
vaccine=pd.read_csv(filename,encoding='cp949')
# 필요없는 열을 삭제한다.
vaccine.drop(['day1sum','day1rate','day2sum','day2rate'], axis=1,inplace=True)
vaccine


# 새로운 열 생성
#vaccine['month']=pd.DatetimeIndex(vaccine['date']).month
#vaccine
# # 월별 평균 출력
#means=vaccine.groupby('month').mean()
#means
#1차 평균 접종수의 월별 그래프
#means['day1num'].plot(kind='bar')
#plt.show()

           date  subject  day1num  day2num
0    2021.10.16  9505868    10673    66910
1    2021.10.15  9505868    14556   133580
2    2021.10.14  9505868     9609    94569
3    2021.10.13  9505868     9804    77503
4    2021.10.12  9505868    17274   110204
..          ...      ...      ...      ...
174  2021.04.25  1023346    23323     3411
175  2021.04.24  1023346      200        0
176  2021.04.23  1027740    10195      119
177  2021.04.22  1023538    27074     2479
178  2021.04.21  1019322    22501     2358

[179 rows x 4 columns]

In [6]:
#문제3-3
vaccine.describe()

            subject        day1num        day2num
count  1.790000e+02     179.000000     179.000000
mean   5.086644e+06   40078.150838   34096.636872
std    3.324235e+06   44231.469656   40745.688278
min    1.019322e+06       0.000000       0.000000
25%    2.279241e+06    4385.000000    4794.500000
50%    3.943320e+06   23323.000000   16581.000000
75%    9.505868e+06   71634.500000   50950.000000
max    9.795426e+06  169036.000000  200186.000000

In [7]:
#문제3-4
# 새로운 열 생성
vaccine['month']=pd.DatetimeIndex(vaccine['date']).month
result=vaccine[['day1num','day2num','month']]
result.groupby('month').mean()

            day1num       day2num
month
4      22060.100000   2304.600000
5      18225.548387   9734.000000
6      55957.200000  20147.300000
7      25807.870968   9934.903226
8      57667.258065  55575.000000
9      65715.000000  62162.000000
10      9406.312500  79900.750000

In [9]:
import pandas as pd
filename1='signup.csv'
filename2='professor.csv'
df1=pd.read_csv(filename1,encoding='cp949')
df2=pd.read_csv(filename2,encoding='cp949')
df1
#df2

   수강코드    과목명 담당교수
0   111    파이썬  양숙희
1   222  데이터분석  오경선
2   333   인공지능  장은실
3   444   선형대수  황복동
4   555   이산수학  정명식
5   666  컴퓨터개론  최봉수
6   777   자료구조  김진영
7   888   정보통신  김진호

In [10]:
df=pd.merge(df1,df2,on='담당교수')
df

   수강코드    과목명 담당교수     학과
0   111    파이썬  양숙희  컴퓨터공학
1   222  데이터분석  오경선   인공지능
2   333   인공지능  장은실   정보통신
3   444   선형대수  황복동  컴퓨터공학
4   555   이산수학  정명식   인공지능

In [11]:
df2.groupby(['학과']).count()

       담당교수
학과
인공지능      2
정보통신      1
컴퓨터공학     2