In [30]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
import requests
import math

In [31]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

if API_KEY:
    print(f'확인 {API_KEY[:6]}...{API_KEY[-4:]}')

확인 a82ec1...e8ad

In [32]:
BASE_URL = 'https://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'

In [33]:
response = requests.get(BASE_URL, params={
    'serviceKey':API_KEY, 
    'pageNo': 1,
    'numOfRows':10,
    '_type':'json',
    'cityCode':22, #대구
    'nodeid':'DGB7041046600'
    })
print(response.status_code) # 상태 확인

200

In [34]:
data = response.json()
data

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'endnodenm': '매곡(종점)',
      'routeid': 'DGB4070003008',
      'routeno': '성서3',
      'routetp': '지선버스',
      'startnodenm': '연화리'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB4070003000',
      'routeno': '성서3',
      'routetp': '지선버스',
      'startnodenm': '연화리'},
     {'endnodenm': '화원유원지(사문진주막촌)',
      'routeid': 'DGB4030003002',
      'routeno': '달서3',
      'routetp': '지선버스',
      'startnodenm': '신흥버스'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB4070003003',
      'routeno': '성서3',
      'routetp': '지선버스',
      'startnodenm': '연화리'},
     {'endnodenm': '매곡(종점)',
      'routeid': 'DGB4070003011',
      'routeno': '성서3',
      'routetp': '지선버스',
      'startnodenm': '연화리'}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 5}}}

In [35]:
data['response']['body']['items']['item']

[{'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003008',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003000',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리'},
 {'endnodenm': '화원유원지(사문진주막촌)',
  'routeid': 'DGB4030003002',
  'routeno': '달서3',
  'routetp': '지선버스',
  'startnodenm': '신흥버스'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003003',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003011',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리'}]

In [36]:
BASE_URL = 'https://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'
CITY_CODE = 22
NODE_ID ='DGB7041046600'
ROWS_PER_PAGE = 50
REQUEST_TIMEOUT = 10

In [37]:
data['response']['body']['totalCount']

5

In [38]:
total_count = data['response']['body']['totalCount']
total_pages = math.ceil(total_count/ ROWS_PER_PAGE)
print(f'{total_count:,}')
print(total_pages)

5
1

In [39]:
import time
all_items = []

for page_no in range(1, total_pages+1):
    params = {
        'serviceKey':API_KEY, 
        'pageNo': page_no,
        'numOfRows':ROWS_PER_PAGE,
        '_type':'json',
        'cityCode': CITY_CODE, #대구
        'nodeid': NODE_ID
    }

    response = requests.get(BASE_URL, params=params, timeout=REQUEST_TIMEOUT)
    response.raise_for_status()

    page_body = response.json()['response']['body']

    if not page_body.get('items'):
        continue

    page_items = page_body['items'].get('item',[])

    if isinstance(page_items, dict):
        page_items = [page_items]

    all_items.extend(page_items)
    print(len(all_items))
    time.sleep(0.2)
print('수집 완료')

5
수집 완료

In [40]:
df_raw = pd.DataFrame(all_items)
df_raw.head()

       endnodenm        routeid routeno routetp startnodenm
0         매곡(종점)  DGB4070003008     성서3    지선버스         연화리
1         매곡(종점)  DGB4070003000     성서3    지선버스         연화리
2  화원유원지(사문진주막촌)  DGB4030003002     달서3    지선버스        신흥버스
3         매곡(종점)  DGB4070003003     성서3    지선버스         연화리
4         매곡(종점)  DGB4070003011     성서3    지선버스         연화리

In [41]:
COLUMN_RENAME = {
    'endnodenm':'종점',
    'routeid':'노선ID', 
    'routeno':'노선번호',
    'routetp':'노선타입',
    'startnodenm':'시점',
}

df = df_raw.rename(columns=COLUMN_RENAME)

df

              종점           노선ID 노선번호  노선타입    시점
0         매곡(종점)  DGB4070003008  성서3  지선버스   연화리
1         매곡(종점)  DGB4070003000  성서3  지선버스   연화리
2  화원유원지(사문진주막촌)  DGB4030003002  달서3  지선버스  신흥버스
3         매곡(종점)  DGB4070003003  성서3  지선버스   연화리
4         매곡(종점)  DGB4070003011  성서3  지선버스   연화리

In [42]:
df['정류장'] = '롯데캐슬그랜드'
df

              종점           노선ID 노선번호  노선타입    시점      정류장
0         매곡(종점)  DGB4070003008  성서3  지선버스   연화리  롯데캐슬그랜드
1         매곡(종점)  DGB4070003000  성서3  지선버스   연화리  롯데캐슬그랜드
2  화원유원지(사문진주막촌)  DGB4030003002  달서3  지선버스  신흥버스  롯데캐슬그랜드
3         매곡(종점)  DGB4070003003  성서3  지선버스   연화리  롯데캐슬그랜드
4         매곡(종점)  DGB4070003011  성서3  지선버스   연화리  롯데캐슬그랜드

In [43]:
df['정류장ID'] = NODE_ID
df

              종점           노선ID 노선번호  노선타입    시점      정류장          정류장ID
0         매곡(종점)  DGB4070003008  성서3  지선버스   연화리  롯데캐슬그랜드  DGB7041046600
1         매곡(종점)  DGB4070003000  성서3  지선버스   연화리  롯데캐슬그랜드  DGB7041046600
2  화원유원지(사문진주막촌)  DGB4030003002  달서3  지선버스  신흥버스  롯데캐슬그랜드  DGB7041046600
3         매곡(종점)  DGB4070003003  성서3  지선버스   연화리  롯데캐슬그랜드  DGB7041046600
4         매곡(종점)  DGB4070003011  성서3  지선버스   연화리  롯데캐슬그랜드  DGB7041046600

### 정류장 추가

In [44]:
# 함수 정의

import time

def get_node_data_list(node_id, node_name):
    all_items = []

    for page_no in range(1, total_pages+1):
        params = {
            'serviceKey':API_KEY, 
            'pageNo': page_no,
            'numOfRows':ROWS_PER_PAGE,
            '_type':'json',
            'cityCode': CITY_CODE, #대구
            'nodeid': node_id
        }

        response = requests.get(BASE_URL, params=params, timeout=REQUEST_TIMEOUT)
        response.raise_for_status()

        page_body = response.json()['response']['body']

        if not page_body.get('items'):
            continue

        page_items = page_body['items'].get('item',[])

        if isinstance(page_items, dict):
            page_items = [page_items]

        all_items.extend(page_items)
        print(len(all_items))
        time.sleep(0.2)
    print('수집 완료')

    # 정류장 이름, 정류장ID 추가
    for ai in all_items:
        ai['node_name'] = node_name
        ai['node_id'] = node_id


    return all_items

In [45]:
NODE_ID_1 = "DGB7041046400" # 용산역(6번출구)
NODE_ID_2 = "DGB7041046700" # 대구지방법원서부지원	
NODE_ID_3 = "DGB7362000578" # 청로1리	
NODE_ID_4 = "DGB7041030800" # 성곡중학교건너

node_l = [(NODE_ID_1,'용산역(6번출구)'), 
          (NODE_ID_2,'대구지방법원서부지원'), 
          (NODE_ID_3,'청로1리'), 
          (NODE_ID_4,'성곡중학교건너')]

In [46]:
all_node = []
for nd, nn in node_l:
    all_node.extend(get_node_data_list(nd,nn))

all_node

4
수집 완료
5
수집 완료
1
수집 완료
1
수집 완료

[{'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003008',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리',
  'node_name': '용산역(6번출구)',
  'node_id': 'DGB7041046400'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003000',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리',
  'node_name': '용산역(6번출구)',
  'node_id': 'DGB7041046400'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003003',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리',
  'node_name': '용산역(6번출구)',
  'node_id': 'DGB7041046400'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003011',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리',
  'node_name': '용산역(6번출구)',
  'node_id': 'DGB7041046400'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003008',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리',
  'node_name': '대구지방법원서부지원',
  'node_id': 'DGB7041046700'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003000',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리',
  'node_name': '대구지방법원서부지원',
  'node_id': 'DGB7041046700'},
 {'endnodenm': '화원유원지(사문진주막촌)',
  'routeid': 'DGB4030003002',
  'routeno': '달서3',
  'routetp': '지선버스',
  'startnodenm': '신흥버스',
  'node_name': '대구지방법원서부지원',
  'node_id': 'DGB7041046700'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003003',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리',
  'node_name': '대구지방법원서부지원',
  'node_id': 'DGB7041046700'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB4070003011',
  'routeno': '성서3',
  'routetp': '지선버스',
  'startnodenm': '연화리',
  'node_name': '대구지방법원서부지원',
  'node_id': 'DGB7041046700'},
 {'endnodenm': '군위공용버스터미널',
  'routeid': 'DGB7361109008',
  'routeno': '군위9',
  'routetp': '마을버스',
  'startnodenm': '군위공용버스터미널',
  'node_name': '청로1리',
  'node_id': 'DGB7362000578'},
 {'endnodenm': '매곡(종점)',
  'routeid': 'DGB3000520000',
  'routeno': 520,
  'routetp': '간선버스',
  'startnodenm': '연화리',
  'node_name': '성곡중학교건너',
  'node_id': 'DGB7041030800'}]

In [47]:
df_plus = pd.DataFrame(all_node)
df_plus

,endnodenm,routeid,routeno,routetp,startnodenm,node_name,node_id
0,매곡(종점),DGB4070003008,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
1,매곡(종점),DGB4070003000,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
2,매곡(종점),DGB4070003003,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
3,매곡(종점),DGB4070003011,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
4,매곡(종점),DGB4070003008,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
5,매곡(종점),DGB4070003000,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
6,화원유원지(사문진주막촌),DGB4030003002,달서3,지선버스,신흥버스,대구지방법원서부지원,DGB7041046700
7,매곡(종점),DGB4070003003,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
8,매곡(종점),DGB4070003011,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
9,군위공용버스터미널,DGB7361109008,군위9,마을버스,군위공용버스터미널,청로1리,DGB7362000578
10,매곡(종점),DGB3000520000,520,간선버스,연화리,성곡중학교건너,DGB7041030800

In [48]:
COLUMN_RENAME = {
    'endnodenm':'종점',
    'routeid':'노선ID', 
    'routeno':'노선번호',
    'routetp':'노선타입',
    'startnodenm':'시점',
    'node_name':'정류장',
    'node_id':'정류장ID',
}

df_plus = df_plus.rename(columns=COLUMN_RENAME)

df_plus

,종점,노선ID,노선번호,노선타입,시점,정류장,정류장ID
0,매곡(종점),DGB4070003008,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
1,매곡(종점),DGB4070003000,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
2,매곡(종점),DGB4070003003,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
3,매곡(종점),DGB4070003011,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
4,매곡(종점),DGB4070003008,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
5,매곡(종점),DGB4070003000,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
6,화원유원지(사문진주막촌),DGB4030003002,달서3,지선버스,신흥버스,대구지방법원서부지원,DGB7041046700
7,매곡(종점),DGB4070003003,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
8,매곡(종점),DGB4070003011,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
9,군위공용버스터미널,DGB7361109008,군위9,마을버스,군위공용버스터미널,청로1리,DGB7362000578
10,매곡(종점),DGB3000520000,520,간선버스,연화리,성곡중학교건너,DGB7041030800

In [55]:
df_new = pd.concat([df, df_plus], axis=0, ignore_index=True)
df_new

,종점,노선ID,노선번호,노선타입,시점,정류장,정류장ID
0,매곡(종점),DGB4070003008,성서3,지선버스,연화리,롯데캐슬그랜드,DGB7041046600
1,매곡(종점),DGB4070003000,성서3,지선버스,연화리,롯데캐슬그랜드,DGB7041046600
2,화원유원지(사문진주막촌),DGB4030003002,달서3,지선버스,신흥버스,롯데캐슬그랜드,DGB7041046600
3,매곡(종점),DGB4070003003,성서3,지선버스,연화리,롯데캐슬그랜드,DGB7041046600
4,매곡(종점),DGB4070003011,성서3,지선버스,연화리,롯데캐슬그랜드,DGB7041046600
5,매곡(종점),DGB4070003008,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
6,매곡(종점),DGB4070003000,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
7,매곡(종점),DGB4070003003,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
8,매곡(종점),DGB4070003011,성서3,지선버스,연화리,용산역(6번출구),DGB7041046400
9,매곡(종점),DGB4070003008,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
10,매곡(종점),DGB4070003000,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
11,화원유원지(사문진주막촌),DGB4030003002,달서3,지선버스,신흥버스,대구지방법원서부지원,DGB7041046700
12,매곡(종점),DGB4070003003,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
13,매곡(종점),DGB4070003011,성서3,지선버스,연화리,대구지방법원서부지원,DGB7041046700
14,군위공용버스터미널,DGB7361109008,군위9,마을버스,군위공용버스터미널,청로1리,DGB7362000578
15,매곡(종점),DGB3000520000,520,간선버스,연화리,성곡중학교건너,DGB7041030800

### DB 저장

In [ ]:
DB_URL = 'postgresql://postgres:1234@Localhost:5432/busapidb'
TABLE_NAME = 'route_by_stop'

def save_to_postgresql(df, db_url, table_name):
    """
    DB 테이블로 저장
    """
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)

    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print(version[:80]+'...')

    # DATAFRAME을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize= 1000,
        method='multi',
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]
        print(saved_count)

In [57]:
save_to_postgresql(df_new, DB_URL, TABLE_NAME)

PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
16