# 정류소별 경유노선 API 조회

## 라이브러리 불러오기

In [1]:
import math
import os 
import time
from datetime import date
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

## API 키 불러오기

In [2]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

if API_KEY:
    print(f'API 키 로드 완료: {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('env파일에 API키를 설정하세요.')

API 키 로드 완료: e6f58a...beaf

### API 연결 테스트

In [3]:
BASE_URL = '	https://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'

In [4]:
response = requests.get(BASE_URL, params={'serviceKey':API_KEY, '_type':'json'})
response.raise_for_status()

In [5]:
print(response.status_code)

200

In [6]:
response = requests.get('http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getCtyCodeList',
                        params={'serviceKey':API_KEY, '_type':'json'})
response

In [7]:
response.json()

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'citycode': 12, 'cityname': '세종특별시'},
     {'citycode': 21, 'cityname': '부산광역시'},
     {'citycode': 22, 'cityname': '대구광역시'},
     {'citycode': 23, 'cityname': '인천광역시'},
     {'citycode': 24, 'cityname': '광주광역시'},
     {'citycode': 25, 'cityname': '대전광역시/계룡시'},
     {'citycode': 26, 'cityname': '울산광역시'},
     {'citycode': 39, 'cityname': '제주도'},
     {'citycode': 31010, 'cityname': '수원시'},
     {'citycode': 31020, 'cityname': '성남시'},
     {'citycode': 31030, 'cityname': '의정부시'},
     {'citycode': 31040, 'cityname': '안양시'},
     {'citycode': 31050, 'cityname': '부천시'},
     {'citycode': 31060, 'cityname': '광명시'},
     {'citycode': 31070, 'cityname': '평택시'},
     {'citycode': 31080, 'cityname': '동두천시'},
     {'citycode': 31090, 'cityname': '안산시'},
     {'citycode': 31100, 'cityname': '고양시'},
     {'citycode': 31110, 'cityname': '과천시'},
     {'citycode': 31120, 'cityname': '구리시'},
     {'citycode': 31130, 'cityname': '남양주시'},
     {'citycode': 31140, 'cityname': '오산시'},
     {'citycode': 31150, 'cityname': '시흥시'},
     {'citycode': 31160, 'cityname': '군포시'},
     {'citycode': 31170, 'cityname': '의왕시'},
     {'citycode': 31180, 'cityname': '하남시'},
     {'citycode': 31190, 'cityname': '용인시'},
     {'citycode': 31200, 'cityname': '파주시'},
     {'citycode': 31210, 'cityname': '이천시'},
     {'citycode': 31220, 'cityname': '안성시'},
     {'citycode': 31230, 'cityname': '김포시'},
     {'citycode': 31240, 'cityname': '화성시'},
     {'citycode': 31250, 'cityname': '광주시'},
     {'citycode': 31260, 'cityname': '양주시'},
     {'citycode': 31270, 'cityname': '포천시'},
     {'citycode': 31320, 'cityname': '여주시'},
     {'citycode': 31350, 'cityname': '연천군'},
     {'citycode': 31370, 'cityname': '가평군'},
     {'citycode': 31380, 'cityname': '양평군'},
     {'citycode': 32010, 'cityname': '춘천시'},
     {'citycode': 32020, 'cityname': '원주시/횡성군'},
     {'citycode': 32050, 'cityname': '태백시'},
     {'citycode': 32310, 'cityname': '홍천군'},
     {'citycode': 32360, 'cityname': '철원군'},
     {'citycode': 32410, 'cityname': '양양군'},
     {'citycode': 33010, 'cityname': '청주시'},
     {'citycode': 33020, 'cityname': '충주시'},
     {'citycode': 33030, 'cityname': '제천시'},
     {'citycode': 33320, 'cityname': '보은군'},
     {'citycode': 33330, 'cityname': '옥천군'},
     {'citycode': 33340, 'cityname': '영동군'},
     {'citycode': 33350, 'cityname': '진천군'},
     {'citycode': 33360, 'cityname': '괴산군'},
     {'citycode': 33370, 'cityname': '음성군'},
     {'citycode': 33380, 'cityname': '단양군'},
     {'citycode': 34010, 'cityname': '천안시'},
     {'citycode': 34020, 'cityname': '공주시'},
     {'citycode': 34030, 'cityname': '보령시'},
     {'citycode': 34040, 'cityname': '아산시'},
     {'citycode': 34050, 'cityname': '서산시'},
     {'citycode': 34060, 'cityname': '논산시'},
     {'citycode': 34070, 'cityname': '계룡시'},
     {'citycode': 34310, 'cityname': '금산군'},
     {'citycode': 34330, 'cityname': '부여군'},
     {'citycode': 34340, 'cityname': '서천군'},
     {'citycode': 34350, 'cityname': '청양군'},
     {'citycode': 34380, 'cityname': '태안군'},
     {'citycode': 34390, 'cityname': '당진시'},
     {'citycode': 35010, 'cityname': '전주시'},
     {'citycode': 35020, 'cityname': '군산시'},
     {'citycode': 35030, 'cityname': '익산시'},
     {'citycode': 35040, 'cityname': '정읍시'},
     {'citycode': 35050, 'cityname': '남원시'},
     {'citycode': 35060, 'cityname': '김제시'},
     {'citycode': 35320, 'cityname': '진안군'},
     {'citycode': 35330, 'cityname': '무주군'},
     {'citycode': 35340, 'cityname': '장수군'},
     {'citycode': 35350, 'cityname': '임실군'},
     {'citycode': 35360, 'cityname': '순창군'},
     {'citycode': 35370, 'cityname': '고창군'},
     {'citycode': 35380, 'cityname': '부안군'},
     {'citycode': 36010, 'cityname': '목포시'},
     {'citycode': 36020, 'cityname': '여수시'},
     {'citycode': 36030, 'cityname': '순천시'},
     {'citycode': 36040, 'cityname': '나주시'},
     {'citycode': 36060, 'cityname': '광양시'},
     {'citycode': 36320, 'cityname': '곡성군'},
     {'citycode': 36330, 'cityname': '구례군'},
     {'citycode': 36350, 'cityname': '고흥군'},
     {'citycode': 36380, 'cityname': '장흥군'},
     {'citycode': 36400, 'cityname': '해남군'},
     {'citycode': 36410, 'cityname': '영암군'},
     {'citycode': 36420, 'cityname': '무안군'},
     {'citycode': 36430, 'cityname': '함평군'},
     {'citycode': 36450, 'cityname': '장성군'},
     {'citycode': 36460, 'cityname': '완도군'},
     {'citycode': 36470, 'cityname': '진도군'},
     {'citycode': 36480, 'cityname': '신안군'},
     {'citycode': 37010, 'cityname': '포항시'},
     {'citycode': 37020, 'cityname': '경주시'},
     {'citycode': 37030, 'cityname': '김천시'},
     {'citycode': 37040, 'cityname': '안동시'},
     {'citycode': 37050, 'cityname': '구미시'},
     {'citycode': 37060, 'cityname': '영주시'},
     {'citycode': 37070, 'cityname': '영천시'},
     {'citycode': 37080, 'cityname': '상주시'},
     {'citycode': 37090, 'cityname': '문경시'},
     {'citycode': 37100, 'cityname': '경산시'},
     {'citycode': 37320, 'cityname': '의성군'},
     {'citycode': 37330, 'cityname': '청송군'},
     {'citycode': 37340, 'cityname': '영양군'},
     {'citycode': 37350, 'cityname': '영덕군'},
     {'citycode': 37360, 'cityname': '청도군'},
     {'citycode': 37370, 'cityname': '고령군'},
     {'citycode': 37380, 'cityname': '성주군'},
     {'citycode': 37390, 'cityname': '칠곡군'},
     {'citycode': 37400, 'cityname': '예천군'},
     {'citycode': 37410, 'cityname': '봉화군'},
     {'citycode': 37420, 'cityname': '울진군'},
     {'citycode': 37430, 'cityname': '울릉군'},
     {'citycode': 38010, 'cityname': '창원시'},
     {'citycode': 38030, 'cityname': '진주시'},
     {'citycode': 38050, 'cityname': '통영시'},
     {'citycode': 38060, 'cityname': '사천시'},
     {'citycode': 38070, 'cityname': '김해시'},
     {'citycode': 38080, 'cityname': '밀양시'},
     {'citycode': 38090, 'cityname': '거제시'},
     {'citycode': 38100, 'cityname': '양산시'},
     {'citycode': 38310, 'cityname': '의령군'},
     {'citycode': 38320, 'cityname': '함안군'},
     {'citycode': 38330, 'cityname': '창녕군'},
     {'citycode': 38340, 'cityname': '고성군'},
     {'citycode': 38350, 'cityname': '남해군'},
     {'citycode': 38360, 'cityname': '하동군'},
     {'citycode': 38370, 'cityname': '산청군'},
     {'citycode': 38380, 'cityname': '함양군'},
     {'citycode': 38390, 'cityname': '거창군'},
     {'citycode': 38400, 'cityname': '합천군'}]}}}}

In [8]:
response = requests.get(BASE_URL, params={'serviceKey': API_KEY, 'pageNo':1, 'numOfRows':10, '_type':'json',
                                            'cityCode':22})
response

In [9]:
response.json()

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'endnodenm': '매곡(종점)',
      'routeid': 'DGB1000001000',
      'routeno': '급행1',
      'routetp': '급행버스',
      'startnodenm': '동화시설집단지구(종점)1'},
     {'endnodenm': '북구 동호동(종점)2(서리지입구)',
      'routeid': 'DGB1000002001',
      'routeno': '급행2',
      'routetp': '급행버스',
      'startnodenm': '냉천전원음식점지구'},
     {'endnodenm': '동명교통',
      'routeid': 'DGB1000003000',
      'routeno': '급행3',
      'routetp': '급행버스',
      'startnodenm': '범물1동행정복지센터건너'},
     {'endnodenm': '신흥버스',
      'routeid': 'DGB1000005000',
      'routeno': '급행5',
      'routetp': '급행버스',
      'startnodenm': '대구대(정문1)'},
     {'endnodenm': '북구 동호동(종점)2(서리지입구)',
      'routeid': 'DGB1000007000',
      'routeno': '급행7',
      'routetp': '급행버스',
      'startnodenm': '남도버스1'},
     {'endnodenm': '서대구역(남측)2',
      'routeid': 'DGB1000008004',
      'routeno': '급행8',
      'routetp': '급행버스',
      'startnodenm': '기업은행국가산단지점건너'},
     {'endnodenm': '진천역(2번출구)',
      'routeid': 'DGB1000008101',
      'routeno': '급행8-1',
      'routetp': '급행버스',
      'startnodenm': '유곡리공영차고지앞'},
     {'endnodenm': '군위군청',
      'routeid': 'DGB1000009002',
      'routeno': '급행9',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '우보버스정류장',
      'routeid': 'DGB1000009100',
      'routeno': '급행9-1',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'},
     {'endnodenm': '삼국유사면문화관',
      'routeid': 'DGB1000009200',
      'routeno': '급행9-2',
      'routetp': '급행버스',
      'startnodenm': '북구 동호동(종점)1'}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 232}}}

In [10]:
data = response.json()
data['response']

{'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
 'body': {'items': {'item': [{'endnodenm': '매곡(종점)',
     'routeid': 'DGB1000001000',
     'routeno': '급행1',
     'routetp': '급행버스',
     'startnodenm': '동화시설집단지구(종점)1'},
    {'endnodenm': '북구 동호동(종점)2(서리지입구)',
     'routeid': 'DGB1000002001',
     'routeno': '급행2',
     'routetp': '급행버스',
     'startnodenm': '냉천전원음식점지구'},
    {'endnodenm': '동명교통',
     'routeid': 'DGB1000003000',
     'routeno': '급행3',
     'routetp': '급행버스',
     'startnodenm': '범물1동행정복지센터건너'},
    {'endnodenm': '신흥버스',
     'routeid': 'DGB1000005000',
     'routeno': '급행5',
     'routetp': '급행버스',
     'startnodenm': '대구대(정문1)'},
    {'endnodenm': '북구 동호동(종점)2(서리지입구)',
     'routeid': 'DGB1000007000',
     'routeno': '급행7',
     'routetp': '급행버스',
     'startnodenm': '남도버스1'},
    {'endnodenm': '서대구역(남측)2',
     'routeid': 'DGB1000008004',
     'routeno': '급행8',
     'routetp': '급행버스',
     'startnodenm': '기업은행국가산단지점건너'},
    {'endnodenm': '진천역(2번출구)',
     'routeid': 'DGB1000008101',
     'routeno': '급행8-1',
     'routetp': '급행버스',
     'startnodenm': '유곡리공영차고지앞'},
    {'endnodenm': '군위군청',
     'routeid': 'DGB1000009002',
     'routeno': '급행9',
     'routetp': '급행버스',
     'startnodenm': '북구 동호동(종점)1'},
    {'endnodenm': '우보버스정류장',
     'routeid': 'DGB1000009100',
     'routeno': '급행9-1',
     'routetp': '급행버스',
     'startnodenm': '북구 동호동(종점)1'},
    {'endnodenm': '삼국유사면문화관',
     'routeid': 'DGB1000009200',
     'routeno': '급행9-2',
     'routetp': '급행버스',
     'startnodenm': '북구 동호동(종점)1'}]},
  'numOfRows': 10,
  'pageNo': 1,
  'totalCount': 232}}

In [11]:
data['response']

{'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
 'body': {'items': {'item': [{'endnodenm': '매곡(종점)',
     'routeid': 'DGB1000001000',
     'routeno': '급행1',
     'routetp': '급행버스',
     'startnodenm': '동화시설집단지구(종점)1'},
    {'endnodenm': '북구 동호동(종점)2(서리지입구)',
     'routeid': 'DGB1000002001',
     'routeno': '급행2',
     'routetp': '급행버스',
     'startnodenm': '냉천전원음식점지구'},
    {'endnodenm': '동명교통',
     'routeid': 'DGB1000003000',
     'routeno': '급행3',
     'routetp': '급행버스',
     'startnodenm': '범물1동행정복지센터건너'},
    {'endnodenm': '신흥버스',
     'routeid': 'DGB1000005000',
     'routeno': '급행5',
     'routetp': '급행버스',
     'startnodenm': '대구대(정문1)'},
    {'endnodenm': '북구 동호동(종점)2(서리지입구)',
     'routeid': 'DGB1000007000',
     'routeno': '급행7',
     'routetp': '급행버스',
     'startnodenm': '남도버스1'},
    {'endnodenm': '서대구역(남측)2',
     'routeid': 'DGB1000008004',
     'routeno': '급행8',
     'routetp': '급행버스',
     'startnodenm': '기업은행국가산단지점건너'},
    {'endnodenm': '진천역(2번출구)',
     'routeid': 'DGB1000008101',
     'routeno': '급행8-1',
     'routetp': '급행버스',
     'startnodenm': '유곡리공영차고지앞'},
    {'endnodenm': '군위군청',
     'routeid': 'DGB1000009002',
     'routeno': '급행9',
     'routetp': '급행버스',
     'startnodenm': '북구 동호동(종점)1'},
    {'endnodenm': '우보버스정류장',
     'routeid': 'DGB1000009100',
     'routeno': '급행9-1',
     'routetp': '급행버스',
     'startnodenm': '북구 동호동(종점)1'},
    {'endnodenm': '삼국유사면문화관',
     'routeid': 'DGB1000009200',
     'routeno': '급행9-2',
     'routetp': '급행버스',
     'startnodenm': '북구 동호동(종점)1'}]},
  'numOfRows': 10,
  'pageNo': 1,
  'totalCount': 232}}

In [12]:
data['response']['body']['items']['item']

[{'endnodenm': '매곡(종점)',
  'routeid': 'DGB1000001000',
  'routeno': '급행1',
  'routetp': '급행버스',
  'startnodenm': '동화시설집단지구(종점)1'},
 {'endnodenm': '북구 동호동(종점)2(서리지입구)',
  'routeid': 'DGB1000002001',
  'routeno': '급행2',
  'routetp': '급행버스',
  'startnodenm': '냉천전원음식점지구'},
 {'endnodenm': '동명교통',
  'routeid': 'DGB1000003000',
  'routeno': '급행3',
  'routetp': '급행버스',
  'startnodenm': '범물1동행정복지센터건너'},
 {'endnodenm': '신흥버스',
  'routeid': 'DGB1000005000',
  'routeno': '급행5',
  'routetp': '급행버스',
  'startnodenm': '대구대(정문1)'},
 {'endnodenm': '북구 동호동(종점)2(서리지입구)',
  'routeid': 'DGB1000007000',
  'routeno': '급행7',
  'routetp': '급행버스',
  'startnodenm': '남도버스1'},
 {'endnodenm': '서대구역(남측)2',
  'routeid': 'DGB1000008004',
  'routeno': '급행8',
  'routetp': '급행버스',
  'startnodenm': '기업은행국가산단지점건너'},
 {'endnodenm': '진천역(2번출구)',
  'routeid': 'DGB1000008101',
  'routeno': '급행8-1',
  'routetp': '급행버스',
  'startnodenm': '유곡리공영차고지앞'},
 {'endnodenm': '군위군청',
  'routeid': 'DGB1000009002',
  'routeno': '급행9',
  'routetp': '급행버스',
  'startnodenm': '북구 동호동(종점)1'},
 {'endnodenm': '우보버스정류장',
  'routeid': 'DGB1000009100',
  'routeno': '급행9-1',
  'routetp': '급행버스',
  'startnodenm': '북구 동호동(종점)1'},
 {'endnodenm': '삼국유사면문화관',
  'routeid': 'DGB1000009200',
  'routeno': '급행9-2',
  'routetp': '급행버스',
  'startnodenm': '북구 동호동(종점)1'}]

In [13]:
data['response']['body']['items']['item'][0]

{'endnodenm': '매곡(종점)',
 'routeid': 'DGB1000001000',
 'routeno': '급행1',
 'routetp': '급행버스',
 'startnodenm': '동화시설집단지구(종점)1'}

In [14]:
data['response']['body']['items']['item'][0]['routeno']

'급행1'

In [15]:
data['response']['body']['items']['item'][0]['routeid']

'DGB1000001000'

### 환경 설정

In [16]:
BASE_URL = 'http://apis.data.go.kr/1613000/BusSttnInfoInqireService/getSttnThrghRouteList'
CITY_CODE = 22
ROWS_PER_PAGE = 1000
REQUEST_TIMEOUT = 10

### 저장 경로

In [17]:
BASE_DIR = os.getcwd()
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'routes_stop.csv')

### PostgreSQL 설정

In [18]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/busapidb'
TABLE_NAME = 'bus_stop'

print(f'csv저장경로 : {OUTPUT_PATH}')

csv저장경로 : c:\Users\Administrator\bigdata2026\fastapi\bus_routes_stop\output\routes_stop.csv

### 전체 데이터 수집

In [19]:
data['response']['body']['totalCount']

232

In [20]:
totla_count = data['response']['body']['totalCount']
total_pages = math.ceil(totla_count / ROWS_PER_PAGE)

print(f'전체 건수 : {totla_count:,}개')
print(f'페이지당 건수 : {ROWS_PER_PAGE:,}개')
print(f'총 페이지 수 : {total_pages}페이지')

전체 건수 : 232개
페이지당 건수 : 1,000개
총 페이지 수 : 1페이지

In [21]:
all_items = []

for page_no in range(1, total_pages+1):
    params={
        'serviceKey' : API_KEY,
        'pageNo' : page_no,
        'numOfRows' : ROWS_PER_PAGE,
        'cityCode'  : CITY_CODE,
        '_type'  : 'json'
    }

    response = requests.get(BASE_URL, params=params, timeout=REQUEST_TIMEOUT)
    response.raise_for_status()

    page_body = response.json()['response']['body']

    if not page_body.get('items'):
        print(f'{page_no} / {total_pages} 페이지: 페이지 없음')
        continue

    page_items = page_body['items'].get('item', [])

    if isinstance(page_items, dict):
        page_items = [page_items]
    
    all_items.extend(page_items)

    print(f'{page_no} / {total_pages} 페이지 수집 완료 -> 누적 {len(all_items):,}건')

    time.sleep(0.2)
    
print(f'전체 수집 완료: {len(all_items):,}건')

1 / 1 페이지 수집 완료 -> 누적 232건
전체 수집 완료: 232건

### DataFrame 만들기

In [22]:
df_raw = pd.DataFrame(all_items)

print(f'데이터프레임의 크기 : {df_raw.shape}')
print(f'컬럼 목록 : {df_raw.columns.tolist()}')

데이터프레임의 크기 : (232, 5)
컬럼 목록 : ['endnodenm', 'routeid', 'routeno', 'routetp', 'startnodenm']

In [23]:
df_raw.head()

            endnodenm        routeid routeno routetp    startnodenm
0              매곡(종점)  DGB1000001000     급행1    급행버스  동화시설집단지구(종점)1
1  북구 동호동(종점)2(서리지입구)  DGB1000002001     급행2    급행버스      냉천전원음식점지구
2                동명교통  DGB1000003000     급행3    급행버스   범물1동행정복지센터건너
3                신흥버스  DGB1000005000     급행5    급행버스       대구대(정문1)
4  북구 동호동(종점)2(서리지입구)  DGB1000007000     급행7    급행버스          남도버스1

### 컬럼명 정리

In [24]:
COLUMN_RENAME = {
    'endnodenm': '종점',
    'routeid': '버스노선id',
    'routeno': '버스번호',
    'routetp': '버스종류',
    'startnodenm': '기점'
}
df = df_raw.rename(columns=COLUMN_RENAME)

print(f'변경 후 컬럼 목록 : {df.columns.tolist()}')

변경 후 컬럼 목록 : ['종점', '버스노선id', '버스번호', '버스종류', '기점']

In [25]:
df.head()

                   종점         버스노선id 버스번호  버스종류             기점
0              매곡(종점)  DGB1000001000  급행1  급행버스  동화시설집단지구(종점)1
1  북구 동호동(종점)2(서리지입구)  DGB1000002001  급행2  급행버스      냉천전원음식점지구
2                동명교통  DGB1000003000  급행3  급행버스   범물1동행정복지센터건너
3                신흥버스  DGB1000005000  급행5  급행버스       대구대(정문1)
4  북구 동호동(종점)2(서리지입구)  DGB1000007000  급행7  급행버스          남도버스1

In [26]:
target_node_id = 'DGB1000001000'

df['node_id'] = target_node_id

In [27]:
df.head()

                   종점         버스노선id 버스번호  버스종류             기점        node_id
0              매곡(종점)  DGB1000001000  급행1  급행버스  동화시설집단지구(종점)1  DGB1000001000
1  북구 동호동(종점)2(서리지입구)  DGB1000002001  급행2  급행버스      냉천전원음식점지구  DGB1000001000
2                동명교통  DGB1000003000  급행3  급행버스   범물1동행정복지센터건너  DGB1000001000
3                신흥버스  DGB1000005000  급행5  급행버스       대구대(정문1)  DGB1000001000
4  북구 동호동(종점)2(서리지입구)  DGB1000007000  급행7  급행버스          남도버스1  DGB1000001000

In [28]:
search_stop_name1 = df['종점']
search_stop_name2 = df['기점']

df['출발지'] = search_stop_name2
df['종착지'] = search_stop_name1

In [30]:
df.head()

,종점,버스노선id,버스번호,버스종류,기점,node_id,출발지,종착지
0,매곡(종점),DGB1000001000,급행1,급행버스,동화시설집단지구(종점)1,DGB1000001000,동화시설집단지구(종점)1,매곡(종점)
1,북구 동호동(종점)2(서리지입구),DGB1000002001,급행2,급행버스,냉천전원음식점지구,DGB1000001000,냉천전원음식점지구,북구 동호동(종점)2(서리지입구)
2,동명교통,DGB1000003000,급행3,급행버스,범물1동행정복지센터건너,DGB1000001000,범물1동행정복지센터건너,동명교통
3,신흥버스,DGB1000005000,급행5,급행버스,대구대(정문1),DGB1000001000,대구대(정문1),신흥버스
4,북구 동호동(종점)2(서리지입구),DGB1000007000,급행7,급행버스,남도버스1,DGB1000001000,남도버스1,북구 동호동(종점)2(서리지입구)

## PostgreSQL 저장

In [31]:
def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL테이블을 저장"""
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] =df_save[col].astype(str)
            
    engine = create_engine(db_url)
    
    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공!')
        print(version + '....')
    
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi',
    )

    with engine.connect() as conn:
        save_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]
    
    print(f'저장완료: {save_count:,}행')
    print(f'DB: busapidb / table: {table_name}')

In [32]:
TABLE_NAME = 'route_by_stop'

In [33]:
save_to_postgresql(df, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit....
저장완료: 232행
DB: busapidb / table: route_by_stop

## CSV 저장

In [34]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

df.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료!')

CSV 저장 완료!

## 최종 결과 요약

In [35]:
TABLE_NAME = 'route_by_stop'

In [36]:
print('=' * 80)
print('정류소별 경유노선 API 조회')
print('=' * 80)
print('수집 방식 : 공공데이터포털 - TAGO REST API')
print(f'도시코드 : {CITY_CODE}(대구)')
print(f'수집 건수 : {len(df):,}건')
print(f'컬럼 수 : {len(df.columns)}개')
print(f'csv 저장 위치 : {OUTPUT_PATH}')
print(f'DB 저장 위치 : busapidb.{TABLE_NAME}')

================================================================================
정류소별 경유노선 API 조회
================================================================================
수집 방식 : 공공데이터포털 - TAGO REST API
도시코드 : 22(대구)
수집 건수 : 232건
컬럼 수 : 8개
csv 저장 위치 : c:\Users\Administrator\bigdata2026\fastapi\bus_routes_stop\output\routes_stop.csv
DB 저장 위치 : busapidb.route_by_stop