In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

# 경로 설정
# ipynb 파일은 getcwd() 함수를 이용해서 파일 위치나 폴더 위치를 가져온다.
BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\2026_07_01'

In [3]:
DATA_PATH = os.path.join(BASE_DIR, "input", "parking.csv") # 경로를 합쳤다.
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\2026_07_01\\input\\parking.csv'

In [4]:
OUTPUT_PATH = os.path.join(BASE_DIR, "output", "parking_new.csv")
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\2026_07_01\\output\\parking_new.csv'

In [ ]:
DB_URL = "postgresql://postgres:1234@localhost:5432/parkingdb"

In [15]:
df = pd.read_csv(DATA_PATH, encoding="cp949")
df.head()

,순번,주차장관리번호,주차장명,주차장 유형,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,주차기본요금,추가단위시간,추가단위요금,1일주차권요금적용시간,1일주차권적용시간,월정기요금,결제방법,관리기관명,경도,위도
0,1,154-1-000001,3공단로25길인근,노상,대구광역시 북구 노원동3가 191-1,6,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.897770,128.565410
1,2,154-1-000002,3공단로인근,노상,대구광역시 북구 노원동3가 14,329,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시청,35.899471,128.569853
2,3,154-1-000003,검단동로인근,노상,대구광역시 북구 검단동 745-2,29,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.913949,128.625135
3,4,154-1-000004,경대로17길인근,노상,대구광역시 북구 복현동 573,78,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892740,128.612720
4,5,154-1-000005,경대로23길인근,노상,대구광역시 북구 복현동 606-34,5,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892602,128.616021

In [9]:
df.shape

(229, 27)

In [10]:
df.columns.tolist()

['순번',
 '주차장관리번호',
 '주차장명',
 '주차장 유형',
 '소재지지번주소',
 '주차구획수',
 '급지구분',
 '부제시행구분',
 '운영요일',
 '평일운영시작시각',
 '평일운영종료시각',
 '토요일운영시작시각',
 '토요일운영종료시각',
 '공휴일운영시작시각',
 '공유일운영종료시각',
 '요금정보',
 '주차기본시간',
 '주차기본요금',
 '추가단위시간',
 '추가단위요금',
 '1일주차권요금적용시간',
 '1일주차권적용시간',
 '월정기요금',
 '결제방법',
 '관리기관명',
 '경도',
 '위도']

In [13]:
null_counts = df.isnull().sum()
if null_counts.any():
    print("결측치 발견")
    print(null_counts[null_counts > 0])
else:
    print("결측치 없음")

결측치 없음

In [14]:
df_new = df[["주차장명", "소재지지번주소", "주차구획수", "운영요일"]]
df_new.head()

        주차장명               소재지지번주소  주차구획수        운영요일
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6  평일+토요일+공휴일
1     3공단로인근     대구광역시 북구 노원동3가 14    329  평일+토요일+공휴일
2     검단동로인근    대구광역시 북구 검단동 745-2     29  평일+토요일+공휴일
3   경대로17길인근      대구광역시 북구 복현동 573     78  평일+토요일+공휴일
4   경대로23길인근   대구광역시 북구 복현동 606-34      5  평일+토요일+공휴일

In [ ]:
# 함수 정의
def save_to_postgresql(df, db_url, table_name):
    """DataFrame을 PostgreSQL 테이블로 저장"""
    df_save = df.copy()

    # pandas 버전 차이에 따라 문자열 컬럼을 str로 정리
    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str) # str로 형변환
    
    engine = create_engine(db_url)

    # DB 연결 테스트
    with engine.connect() as conn:
        version = conn.execute(text("SELECT version();")).fetchone()[0]
        print("PostgreSQL 연결 성공!")
        print(version[:80] + "...")

    # 데이터프레임을 DB 테이블로 저장
    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists="replace",
        index=False,
        chunksize=1000,
        method="multi",
    )

    # 저장 건수 확인
    with engine.connect() as conn:
        saved_count = conn.execute(text(f"SELECT COUNT(*) FROM {table_name};")).fetchone()[0]

    print(f"{saved_count}행 저장 완료")
    print(f"DB : subwaydb / table : {table_name}")